// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void slide_Animation(lv_obj_t * TargetObject, int delay);
void slideup_Animation(lv_obj_t * TargetObject, int delay);
void slidedown_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
lv_obj_t * ui_Loading_Screen;
lv_obj_t * ui_Loading_Screen_Logo_Image;
lv_obj_t * ui_Loading_Screen__Loading_Label;
lv_obj_t * ui_Loading_Screen_Panel1;
// CUSTOM VARIABLES
lv_obj_t * uic_Loading_Screen;
lv_obj_t * uic_Loading_Screen_Logo_Image;
lv_obj_t * uic_Loading_Screen__Loading_Label;


// SCREEN: ui_Radio_Screen
void ui_Radio_Screen_screen_init(void);
lv_obj_t * ui_Radio_Screen;
lv_obj_t * ui_Radio_Screen_Artist;
lv_obj_t * ui_Radio_Screen_Station;
lv_obj_t * ui_Radio_Screen_Commercial;
lv_obj_t * ui_Radio_Screen_Title;
void ui_event_Radio_Screen_No_WIFI_Image(lv_event_t * e);
lv_obj_t * ui_Radio_Screen_No_WIFI_Image;
void ui_event_Radio_Screen_WIFI_Image(lv_event_t * e);
lv_obj_t * ui_Radio_Screen_WIFI_Image;
lv_obj_t * ui_Radio_Screen_Line_Image;
lv_obj_t * ui_Radio_Screen_Clock_Label;
lv_obj_t * ui_Radio_Screen_Panel_Tray;
void ui_event_Radio_Screen_Mode_Button(lv_event_t * e);
lv_obj_t * ui_Radio_Screen_Mode_Button;
lv_obj_t * ui_Radio_Screen_Mode_Button_Label;
void ui_event_Radio_Screen_Tune_Button(lv_event_t * e);
lv_obj_t * ui_Radio_Screen_Tune_Button;
lv_obj_t * ui_Radio_Screen_Tune_Button_Label;
void ui_event_Radio_Screen_Button_Tray_Up(lv_event_t * e);
lv_obj_t * ui_Radio_Screen_Button_Tray_Up;
lv_obj_t * ui_Radio_Screen_Button_Tray_Up_Image;
void ui_event_Radio_Screen_Button_Tray_Down(lv_event_t * e);
lv_obj_t * ui_Radio_Screen_Button_Tray_Down;
lv_obj_t * ui_Radio_Screen_Button_Tray_Down_Image;
// CUSTOM VARIABLES
lv_obj_t * uic_Radio_Screen;
lv_obj_t * uic_Radio_Screen_Artist;
lv_obj_t * uic_Radio_Screen_Station;
lv_obj_t * uic_Radio_Screen_Commercial;
lv_obj_t * uic_Radio_Screen_Title;
lv_obj_t * uic_Radio_Screen_No_WIFI_Image;
lv_obj_t * uic_Radio_Screen_WIFI_Image;
lv_obj_t * uic_Radio_Screen_Line_Image;
lv_obj_t * uic_Radio_Screen_Clock_Label;
lv_obj_t * uic_Radio_Screen_Panel_Tray;
lv_obj_t * uic_Radio_Screen_Mode_Button;
lv_obj_t * uic_Radio_Screen_Mode_Button_Label;
lv_obj_t * uic_Radio_Screen_Tune_Button;
lv_obj_t * uic_Radio_Screen_Tune_Button_Label;
lv_obj_t * uic_Radio_Screen_Button_Tray_Up;
lv_obj_t * uic_Radio_Screen_Button_Tray_Up_Image;
lv_obj_t * uic_Radio_Screen_Button_Tray_Down;
lv_obj_t * uic_Radio_Screen_Button_Tray_Down_Image;


// SCREEN: ui_Volume_Screen
void ui_Volume_Screen_screen_init(void);
void ui_event_Volume_Screen(lv_event_t * e);
lv_obj_t * ui_Volume_Screen;
lv_obj_t * ui_Volume_Screen_Slider;
// CUSTOM VARIABLES
lv_obj_t * uic_Volume_Screen_Slider;


// SCREEN: ui_Network_Screen
void ui_Network_Screen_screen_init(void);
lv_obj_t * ui_Network_Screen;
void ui_event_Network_Screen_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Network_Screen_Keyboard1;
void ui_event_Network_Screen_SSID_Text_Area(lv_event_t * e);
lv_obj_t * ui_Network_Screen_SSID_Text_Area;
void ui_event_Network_Screen_Password_Text_Area(lv_event_t * e);
lv_obj_t * ui_Network_Screen_Password_Text_Area;
void ui_event_Network_Screen_Cancel_Button(lv_event_t * e);
lv_obj_t * ui_Network_Screen_Cancel_Button;
lv_obj_t * ui_Network_Screen_Cancel_Button_Label;
// CUSTOM VARIABLES
lv_obj_t * uic_Network_Screen;
lv_obj_t * uic_Network_Screen_Keyboard1;
lv_obj_t * uic_Network_Screen_SSID_Text_Area;
lv_obj_t * uic_Network_Screen_Password_Text_Area;
lv_obj_t * uic_Network_Screen_Cancel_Button;
lv_obj_t * uic_Network_Screen_Cancel_Button_Label;


// SCREEN: ui_Mode_Screen
void ui_Mode_Screen_screen_init(void);
lv_obj_t * ui_Mode_Screen;
lv_obj_t * ui_Mode_Screen_Mode_Roller;
void ui_event_Mode_Screen_Cancel_Button(lv_event_t * e);
lv_obj_t * ui_Mode_Screen_Cancel_Button;
lv_obj_t * ui_Mode_Screen_Cancel_Button_Label;
void ui_event_Mode_Screen_Select_Button(lv_event_t * e);
lv_obj_t * ui_Mode_Screen_Select_Button;
lv_obj_t * ui_Mode_Screen_Select_Button_Label;
// CUSTOM VARIABLES
lv_obj_t * uic_Mode_Screen;
lv_obj_t * uic_Mode_Screen_Mode_Roller;
lv_obj_t * uic_Mode_Screen_Cancel_Button_Label;
lv_obj_t * uic_Mode_Screen_Select_Button;
lv_obj_t * uic_Mode_Screen_Select_Button_Label;


// SCREEN: ui_Station_Selection_Screen
void ui_Station_Selection_Screen_screen_init(void);
lv_obj_t * ui_Station_Selection_Screen;
void ui_event_Station_Selection_Screen_Play_Button(lv_event_t * e);
lv_obj_t * ui_Station_Selection_Screen_Play_Button;
lv_obj_t * ui_Station_Selection_Screen_Play_Button_Label;
void ui_event_Station_Selection_Screen_Cancel_Button(lv_event_t * e);
lv_obj_t * ui_Station_Selection_Screen_Cancel_Button;
lv_obj_t * ui_Station_Selection_Screen_Cancel_Button_Label;
void ui_event_Station_Selection_Screen_Roller(lv_event_t * e);
lv_obj_t * ui_Station_Selection_Screen_Roller;
// CUSTOM VARIABLES
lv_obj_t * uic_Station_Selection_Screen;
lv_obj_t * uic_Station_Selection_Screen_Play_Button;
lv_obj_t * uic_Station_Selection_Screen_Play_Button_Label;
lv_obj_t * uic_Station_Selection_Screen_Cancel_Button;
lv_obj_t * uic_Station_Selection_Screen_Cancel_Button_Label;
lv_obj_t * uic_Station_Selection_Screen_Roller;


// SCREEN: ui_Clock_Screen
void ui_Clock_Screen_screen_init(void);
lv_obj_t * ui_Clock_Screen;
lv_obj_t * ui_Clock_Screen_Clock_Label;
lv_obj_t * ui_Clock_Screen_Panel_Tray;
void ui_event_Clock_Screen_Mode_Button(lv_event_t * e);
lv_obj_t * ui_Clock_Screen_Mode_Button;
lv_obj_t * ui_Clock_Screen_Mode_Button_Label;
void ui_event_Clock_Screen_Tune_Settings_Button(lv_event_t * e);
lv_obj_t * ui_Clock_Screen_Tune_Settings_Button;
lv_obj_t * ui_Clock_Screen_Settings_Button_Label;
void ui_event_Clock_Screen_Button_Tray_Up(lv_event_t * e);
lv_obj_t * ui_Clock_Screen_Button_Tray_Up;
lv_obj_t * ui_Clock_Screen_Button_Tray_Up_Image;
void ui_event_Clock_Screen_Button_Tray_Down(lv_event_t * e);
lv_obj_t * ui_Clock_Screen_Button_Tray_Down;
lv_obj_t * ui_Clock_Screen_Button_Tray_Down_Image;
// CUSTOM VARIABLES
lv_obj_t * uic_Clock_Screen;
lv_obj_t * uic_Clock_Screen_Clock_Label;
lv_obj_t * uic_Clock_Screen_Panel_Tray;
lv_obj_t * uic_Clock_Screen_Mode_Button;
lv_obj_t * uic_Clock_Screen_Mode_Button_Label2;
lv_obj_t * uic_Clock_Screen_Tune_Settings_Button;
lv_obj_t * uic_Clock_Screen_Settings_Button_Label;
lv_obj_t * uic_Clock_Screen_Button_Tray_Up;
lv_obj_t * uic_Clock_Screen_Button_Tray_Up_Image;
lv_obj_t * uic_Clock_Screen_Button_Tray_Down;
lv_obj_t * uic_Clock_Screen_Button_Tray_Down_Image;


// SCREEN: ui_Message_Screen
void ui_Message_Screen_screen_init(void);
lv_obj_t * ui_Message_Screen;
lv_obj_t * ui_Message_Screen_Message_Label;
// CUSTOM VARIABLES
lv_obj_t * uic_Message_Screen;
lv_obj_t * uic_Message_Screen_Message_Label;


// SCREEN: ui_Configuration_Screen
void ui_Configuration_Screen_screen_init(void);
lv_obj_t * ui_Configuration_Screen;
lv_obj_t * ui_Configuration_Screen_Button1;
lv_obj_t * ui_Configuration_Screen_Button2;
lv_obj_t * ui_Configuration_Screen_Button3;
lv_obj_t * ui_Configuration_Screen_Button4;
// CUSTOM VARIABLES
lv_obj_t * uic_Configuration_Screen;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void slide_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void slideup_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 139, 69);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, -100);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void slidedown_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 69, 139);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Radio_Screen_No_WIFI_Image(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Network_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Network_Screen_screen_init);
    }
}

void ui_event_Radio_Screen_WIFI_Image(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Network_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Network_Screen_screen_init);
    }
}

void ui_event_Radio_Screen_Mode_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Mode_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Mode_Screen_screen_init);
        slidedown_Animation(ui_Radio_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Radio_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Radio_Screen_Tune_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Station_Selection_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0,
                          &ui_Station_Selection_Screen_screen_init);
        slidedown_Animation(ui_Radio_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Radio_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Radio_Screen_Button_Tray_Up(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        slideup_Animation(ui_Radio_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Radio_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Radio_Screen_Button_Tray_Down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Radio_Screen_Button_Tray_Down(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        slidedown_Animation(ui_Radio_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Radio_Screen_Button_Tray_Down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Radio_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Volume_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_Volume_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Volume_Screen_screen_init);
    }
}

void ui_event_Network_Screen_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        keyboardReadyKey(e);
        _ui_screen_change(&ui_Radio_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Radio_Screen_screen_init);
    }
}

void ui_event_Network_Screen_SSID_Text_Area(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Network_Screen_Keyboard1,  ui_Network_Screen_SSID_Text_Area);
    }
}

void ui_event_Network_Screen_Password_Text_Area(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Network_Screen_Keyboard1,  ui_Network_Screen_Password_Text_Area);
    }
}

void ui_event_Network_Screen_Cancel_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        cancelNetworkScreen(e);
        _ui_screen_change(&ui_Radio_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Radio_Screen_screen_init);
    }
}

void ui_event_Mode_Screen_Cancel_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Radio_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Radio_Screen_screen_init);
    }
}

void ui_event_Mode_Screen_Select_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        modeSelected(e);
    }
}

void ui_event_Station_Selection_Screen_Play_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        playStation(e);
    }
}

void ui_event_Station_Selection_Screen_Cancel_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Radio_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Radio_Screen_screen_init);
    }
}

void ui_event_Station_Selection_Screen_Roller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        stationSelectionChanged(e);
    }
}

void ui_event_Clock_Screen_Mode_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Mode_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Mode_Screen_screen_init);
        slidedown_Animation(ui_Clock_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Clock_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Clock_Screen_Tune_Settings_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        slidedown_Animation(ui_Clock_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Clock_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Clock_Screen_Button_Tray_Up(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        slideup_Animation(ui_Clock_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Clock_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Clock_Screen_Button_Tray_Down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Clock_Screen_Button_Tray_Down(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        slidedown_Animation(ui_Clock_Screen_Panel_Tray, 0);
        _ui_flag_modify(ui_Clock_Screen_Button_Tray_Down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Clock_Screen_Button_Tray_Up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Loading_Screen_screen_init();
    ui_Radio_Screen_screen_init();
    ui_Volume_Screen_screen_init();
    ui_Network_Screen_screen_init();
    ui_Mode_Screen_screen_init();
    ui_Station_Selection_Screen_screen_init();
    ui_Clock_Screen_screen_init();
    ui_Message_Screen_screen_init();
    ui_Configuration_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Loading_Screen);
}
