// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#ifndef _SQUARELINE_UI_H
#define _SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void slide_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
void ui_event_Loading_Screen(lv_event_t * e);
extern lv_obj_t * ui_Loading_Screen;
extern lv_obj_t * ui_Loading_Screen_Logo_Image;
extern lv_obj_t * ui_Loading_Screen__Loading_Label;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Loading_Screen;
extern lv_obj_t * uic_Loading_Screen_Logo_Image;
extern lv_obj_t * uic_Loading_Screen__Loading_Label;

// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
extern lv_obj_t * ui_Main_Screen;
extern lv_obj_t * ui_Main_Screen_Title;
extern lv_obj_t * ui_Main_Screen_Artist;
extern lv_obj_t * ui_Main_Screen_Station;
extern lv_obj_t * ui_Main_Screen_No_WIFI_Image;
extern lv_obj_t * ui_Main_Screen_WIFI_Image;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Main_Screen;
extern lv_obj_t * uic_Main_Screen_Title;
extern lv_obj_t * uic_Main_Screen_Artist;
extern lv_obj_t * uic_Main_Screen_Station;
extern lv_obj_t * uic_Main_Screen_No_WIFI_Image;
extern lv_obj_t * uic_Main_Screen_WIFI_Image;

// SCREEN: ui_Volume_Screen
void ui_Volume_Screen_screen_init(void);
void ui_event_Volume_Screen(lv_event_t * e);
extern lv_obj_t * ui_Volume_Screen;
extern lv_obj_t * ui_Volume_Screen_Slider;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Volume_Screen_Slider;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bitdog_flattened_png);    // assets/Bitdog_flattened.png
LV_IMG_DECLARE(ui_img_1771336624);    // assets/no-wifi-small.png
LV_IMG_DECLARE(ui_img_696732886);    // assets/wifi-small.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
