// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"

void ui_Clock_Screen_screen_init(void)
{
    ui_Clock_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Clock_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock_Screen, &ui_font_Tech, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Clock_Label = lv_label_create(ui_Clock_Screen);
    lv_obj_set_width(ui_Clock_Screen_Clock_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Screen_Clock_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock_Screen_Clock_Label, 0);
    lv_obj_set_y(ui_Clock_Screen_Clock_Label, -11);
    lv_obj_set_align(ui_Clock_Screen_Clock_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock_Screen_Clock_Label, "11:20 PM");
    lv_obj_set_style_text_color(ui_Clock_Screen_Clock_Label, lv_color_hex(0xF02121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clock_Screen_Clock_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock_Screen_Clock_Label, &ui_font_tech72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Panel_Tray = lv_obj_create(ui_Clock_Screen);
    lv_obj_set_width(ui_Clock_Screen_Panel_Tray, 331);
    lv_obj_set_height(ui_Clock_Screen_Panel_Tray, 83);
    lv_obj_set_x(ui_Clock_Screen_Panel_Tray, 0);
    lv_obj_set_y(ui_Clock_Screen_Panel_Tray, 139);
    lv_obj_set_align(ui_Clock_Screen_Panel_Tray, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Clock_Screen_Panel_Tray, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen_Panel_Tray, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen_Panel_Tray, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Clock_Screen_Panel_Tray, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Clock_Screen_Panel_Tray, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Clock_Screen_Panel_Tray, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Clock_Screen_Panel_Tray, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Mode_Button = lv_button_create(ui_Clock_Screen_Panel_Tray);
    lv_obj_set_width(ui_Clock_Screen_Mode_Button, 100);
    lv_obj_set_height(ui_Clock_Screen_Mode_Button, 38);
    lv_obj_set_x(ui_Clock_Screen_Mode_Button, 0);
    lv_obj_set_y(ui_Clock_Screen_Mode_Button, 8);
    lv_obj_add_flag(ui_Clock_Screen_Mode_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Clock_Screen_Mode_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen_Mode_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen_Mode_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Clock_Screen_Mode_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Clock_Screen_Mode_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Clock_Screen_Mode_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Clock_Screen_Mode_Button, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Clock_Screen_Mode_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Clock_Screen_Mode_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Mode_Button_Label = lv_label_create(ui_Clock_Screen_Mode_Button);
    lv_obj_set_width(ui_Clock_Screen_Mode_Button_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Screen_Mode_Button_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Clock_Screen_Mode_Button_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock_Screen_Mode_Button_Label, "Mode");
    lv_obj_set_style_text_font(ui_Clock_Screen_Mode_Button_Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Tune_Settings_Button = lv_button_create(ui_Clock_Screen_Panel_Tray);
    lv_obj_set_width(ui_Clock_Screen_Tune_Settings_Button, 100);
    lv_obj_set_height(ui_Clock_Screen_Tune_Settings_Button, 38);
    lv_obj_set_x(ui_Clock_Screen_Tune_Settings_Button, 202);
    lv_obj_set_y(ui_Clock_Screen_Tune_Settings_Button, 8);
    lv_obj_add_flag(ui_Clock_Screen_Tune_Settings_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Clock_Screen_Tune_Settings_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen_Tune_Settings_Button, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen_Tune_Settings_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Clock_Screen_Tune_Settings_Button, lv_color_hex(0xFFFFFF),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Clock_Screen_Tune_Settings_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Clock_Screen_Tune_Settings_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Clock_Screen_Tune_Settings_Button, LV_BORDER_SIDE_FULL,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Clock_Screen_Tune_Settings_Button, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Clock_Screen_Tune_Settings_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Settings_Button_Label = lv_label_create(ui_Clock_Screen_Tune_Settings_Button);
    lv_obj_set_width(ui_Clock_Screen_Settings_Button_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Screen_Settings_Button_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Clock_Screen_Settings_Button_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock_Screen_Settings_Button_Label, "Tune");
    lv_obj_set_style_text_font(ui_Clock_Screen_Settings_Button_Label, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Button_Tray_Up = lv_button_create(ui_Clock_Screen_Panel_Tray);
    lv_obj_set_width(ui_Clock_Screen_Button_Tray_Up, 84);
    lv_obj_set_height(ui_Clock_Screen_Button_Tray_Up, 30);
    lv_obj_set_x(ui_Clock_Screen_Button_Tray_Up, 0);
    lv_obj_set_y(ui_Clock_Screen_Button_Tray_Up, -30);
    lv_obj_set_align(ui_Clock_Screen_Button_Tray_Up, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Clock_Screen_Button_Tray_Up, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Clock_Screen_Button_Tray_Up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen_Button_Tray_Up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen_Button_Tray_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Clock_Screen_Button_Tray_Up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Clock_Screen_Button_Tray_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Clock_Screen_Button_Tray_Up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Clock_Screen_Button_Tray_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Button_Tray_Up_Image = lv_image_create(ui_Clock_Screen_Button_Tray_Up);
    lv_image_set_src(ui_Clock_Screen_Button_Tray_Up_Image, &ui_img_up_png);
    lv_obj_set_width(ui_Clock_Screen_Button_Tray_Up_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Screen_Button_Tray_Up_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Clock_Screen_Button_Tray_Up_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Clock_Screen_Button_Tray_Up_Image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Clock_Screen_Button_Tray_Up_Image,
                       LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Clock_Screen_Button_Tray_Up_Image, 150);

    ui_Clock_Screen_Button_Tray_Down = lv_button_create(ui_Clock_Screen_Panel_Tray);
    lv_obj_set_width(ui_Clock_Screen_Button_Tray_Down, 60);
    lv_obj_set_height(ui_Clock_Screen_Button_Tray_Down, 30);
    lv_obj_set_x(ui_Clock_Screen_Button_Tray_Down, 0);
    lv_obj_set_y(ui_Clock_Screen_Button_Tray_Down, 33);
    lv_obj_set_align(ui_Clock_Screen_Button_Tray_Down, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Clock_Screen_Button_Tray_Down, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Clock_Screen_Button_Tray_Down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen_Button_Tray_Down, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen_Button_Tray_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Clock_Screen_Button_Tray_Down, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Clock_Screen_Button_Tray_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Button_Tray_Down_Image = lv_image_create(ui_Clock_Screen_Button_Tray_Down);
    lv_image_set_src(ui_Clock_Screen_Button_Tray_Down_Image, &ui_img_down_png);
    lv_obj_set_width(ui_Clock_Screen_Button_Tray_Down_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Screen_Button_Tray_Down_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock_Screen_Button_Tray_Down_Image, 0);
    lv_obj_set_y(ui_Clock_Screen_Button_Tray_Down_Image, 4);
    lv_obj_set_align(ui_Clock_Screen_Button_Tray_Down_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Clock_Screen_Button_Tray_Down_Image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Clock_Screen_Button_Tray_Down_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Clock_Screen_Button_Tray_Down_Image, 150);

    lv_obj_add_event_cb(ui_Clock_Screen_Mode_Button, ui_event_Clock_Screen_Mode_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Clock_Screen_Tune_Settings_Button, ui_event_Clock_Screen_Tune_Settings_Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_Clock_Screen_Button_Tray_Up, ui_event_Clock_Screen_Button_Tray_Up, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Clock_Screen_Button_Tray_Down, ui_event_Clock_Screen_Button_Tray_Down, LV_EVENT_ALL, NULL);
    uic_Clock_Screen = ui_Clock_Screen;
    uic_Clock_Screen_Clock_Label = ui_Clock_Screen_Clock_Label;
    uic_Clock_Screen_Panel_Tray = ui_Clock_Screen_Panel_Tray;
    uic_Clock_Screen_Mode_Button = ui_Clock_Screen_Mode_Button;
    uic_Clock_Screen_Mode_Button_Label2 = ui_Clock_Screen_Mode_Button_Label;
    uic_Clock_Screen_Tune_Settings_Button = ui_Clock_Screen_Tune_Settings_Button;
    uic_Clock_Screen_Settings_Button_Label = ui_Clock_Screen_Settings_Button_Label;
    uic_Clock_Screen_Button_Tray_Up = ui_Clock_Screen_Button_Tray_Up;
    uic_Clock_Screen_Button_Tray_Up_Image = ui_Clock_Screen_Button_Tray_Up_Image;
    uic_Clock_Screen_Button_Tray_Down = ui_Clock_Screen_Button_Tray_Down;
    uic_Clock_Screen_Button_Tray_Down_Image = ui_Clock_Screen_Button_Tray_Down_Image;

}
