// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"

void ui_Clock_Screen_screen_init(void)
{
    ui_Clock_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Clock_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock_Screen, &ui_font_Tech, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Screen_Clock_Label = lv_label_create(ui_Clock_Screen);
    lv_obj_set_width(ui_Clock_Screen_Clock_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Screen_Clock_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock_Screen_Clock_Label, 0);
    lv_obj_set_y(ui_Clock_Screen_Clock_Label, -11);
    lv_obj_set_align(ui_Clock_Screen_Clock_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock_Screen_Clock_Label, "11:20 PM");
    lv_obj_set_style_text_color(ui_Clock_Screen_Clock_Label, lv_color_hex(0xF02121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clock_Screen_Clock_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock_Screen_Clock_Label, &ui_font_tech72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Clock_Screen, ui_event_Clock_Screen, LV_EVENT_ALL, NULL);
    uic_Clock_Screen = ui_Clock_Screen;
    uic_Clock_Screen_Clock_Label = ui_Clock_Screen_Clock_Label;

}
