// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"

void ui_Configuration_Screen_screen_init(void)
{
    ui_Configuration_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Configuration_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Configuration_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Configuration_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Configuration_Screen_Button1 = lv_button_create(ui_Configuration_Screen);
    lv_obj_set_width(ui_Configuration_Screen_Button1, 100);
    lv_obj_set_height(ui_Configuration_Screen_Button1, 50);
    lv_obj_set_x(ui_Configuration_Screen_Button1, -83);
    lv_obj_set_y(ui_Configuration_Screen_Button1, 48);
    lv_obj_set_align(ui_Configuration_Screen_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Configuration_Screen_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Configuration_Screen_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Configuration_Screen_Button2 = lv_button_create(ui_Configuration_Screen);
    lv_obj_set_width(ui_Configuration_Screen_Button2, 100);
    lv_obj_set_height(ui_Configuration_Screen_Button2, 50);
    lv_obj_set_x(ui_Configuration_Screen_Button2, 61);
    lv_obj_set_y(ui_Configuration_Screen_Button2, 42);
    lv_obj_set_align(ui_Configuration_Screen_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Configuration_Screen_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Configuration_Screen_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Configuration_Screen_Button3 = lv_button_create(ui_Configuration_Screen);
    lv_obj_set_width(ui_Configuration_Screen_Button3, 100);
    lv_obj_set_height(ui_Configuration_Screen_Button3, 50);
    lv_obj_set_x(ui_Configuration_Screen_Button3, -96);
    lv_obj_set_y(ui_Configuration_Screen_Button3, -74);
    lv_obj_set_align(ui_Configuration_Screen_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Configuration_Screen_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Configuration_Screen_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Configuration_Screen_Button4 = lv_button_create(ui_Configuration_Screen);
    lv_obj_set_width(ui_Configuration_Screen_Button4, 100);
    lv_obj_set_height(ui_Configuration_Screen_Button4, 50);
    lv_obj_set_x(ui_Configuration_Screen_Button4, 77);
    lv_obj_set_y(ui_Configuration_Screen_Button4, -74);
    lv_obj_set_align(ui_Configuration_Screen_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Configuration_Screen_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Configuration_Screen_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Configuration_Screen = ui_Configuration_Screen;

}
