// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"

void ui_Loading_Screen_screen_init(void)
{
    ui_Loading_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Loading_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Loading_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loading_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Loading_Screen_Logo_Image = lv_image_create(ui_Loading_Screen);
    lv_image_set_src(ui_Loading_Screen_Logo_Image, &ui_img_bitdog_flattened_png);
    lv_obj_set_width(ui_Loading_Screen_Logo_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Loading_Screen_Logo_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Loading_Screen_Logo_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Loading_Screen_Logo_Image, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Loading_Screen_Logo_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Loading_Screen_Logo_Image, 300);

    ui_Loading_Screen__Loading_Label = lv_label_create(ui_Loading_Screen);
    lv_obj_set_width(ui_Loading_Screen__Loading_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Loading_Screen__Loading_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Loading_Screen__Loading_Label, 0);
    lv_obj_set_y(ui_Loading_Screen__Loading_Label, 89);
    lv_obj_set_align(ui_Loading_Screen__Loading_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Loading_Screen__Loading_Label, "Loading,,,");
    lv_obj_set_style_text_color(ui_Loading_Screen__Loading_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Loading_Screen__Loading_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Loading_Screen = ui_Loading_Screen;
    uic_Loading_Screen_Logo_Image = ui_Loading_Screen_Logo_Image;
    uic_Loading_Screen__Loading_Label = ui_Loading_Screen__Loading_Label;

}
