// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"

void ui_Network_Screen_screen_init(void)
{
    ui_Network_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Network_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Network_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Network_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network_Screen_Keyboard1 = lv_keyboard_create(ui_Network_Screen);
    lv_obj_set_width(ui_Network_Screen_Keyboard1, 311);
    lv_obj_set_height(ui_Network_Screen_Keyboard1, 120);
    lv_obj_set_x(ui_Network_Screen_Keyboard1, -1);
    lv_obj_set_y(ui_Network_Screen_Keyboard1, -4);

    ui_Network_Screen_SSID_Text_Area = lv_textarea_create(ui_Network_Screen);
    lv_obj_set_width(ui_Network_Screen_SSID_Text_Area, 200);
    lv_obj_set_height(ui_Network_Screen_SSID_Text_Area, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Network_Screen_SSID_Text_Area, 10);
    lv_obj_set_y(ui_Network_Screen_SSID_Text_Area, 8);
    lv_textarea_set_placeholder_text(ui_Network_Screen_SSID_Text_Area, "Network SSID Name");
    lv_textarea_set_one_line(ui_Network_Screen_SSID_Text_Area, true);



    ui_Network_Screen_Password_Text_Area = lv_textarea_create(ui_Network_Screen);
    lv_obj_set_width(ui_Network_Screen_Password_Text_Area, 200);
    lv_obj_set_height(ui_Network_Screen_Password_Text_Area, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Network_Screen_Password_Text_Area, 10);
    lv_obj_set_y(ui_Network_Screen_Password_Text_Area, 53);
    lv_textarea_set_placeholder_text(ui_Network_Screen_Password_Text_Area, "Password");
    lv_textarea_set_one_line(ui_Network_Screen_Password_Text_Area, true);
    lv_textarea_set_password_mode(ui_Network_Screen_Password_Text_Area, true);



    ui_Network_Screen_Cancel_Button = lv_button_create(ui_Network_Screen);
    lv_obj_set_width(ui_Network_Screen_Cancel_Button, 71);
    lv_obj_set_height(ui_Network_Screen_Cancel_Button, 76);
    lv_obj_set_x(ui_Network_Screen_Cancel_Button, 104);
    lv_obj_set_y(ui_Network_Screen_Cancel_Button, -72);
    lv_obj_set_align(ui_Network_Screen_Cancel_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Network_Screen_Cancel_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Network_Screen_Cancel_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Network_Screen_Cancel_Button_Label = lv_label_create(ui_Network_Screen_Cancel_Button);
    lv_obj_set_width(ui_Network_Screen_Cancel_Button_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Network_Screen_Cancel_Button_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Network_Screen_Cancel_Button_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Network_Screen_Cancel_Button_Label, "Cancel");

    lv_obj_add_event_cb(ui_Network_Screen_Keyboard1, ui_event_Network_Screen_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Network_Screen_SSID_Text_Area, ui_event_Network_Screen_SSID_Text_Area, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Network_Screen_Password_Text_Area, ui_event_Network_Screen_Password_Text_Area, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_Network_Screen_Cancel_Button, ui_event_Network_Screen_Cancel_Button, LV_EVENT_ALL, NULL);
    uic_Network_Screen = ui_Network_Screen;
    uic_Network_Screen_Keyboard1 = ui_Network_Screen_Keyboard1;
    uic_Network_Screen_SSID_Text_Area = ui_Network_Screen_SSID_Text_Area;
    uic_Network_Screen_Password_Text_Area = ui_Network_Screen_Password_Text_Area;
    uic_Network_Screen_Cancel_Button = ui_Network_Screen_Cancel_Button;
    uic_Network_Screen_Cancel_Button_Label = ui_Network_Screen_Cancel_Button_Label;

}
