// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"

void ui_Tune_Screen_screen_init(void)
{
    ui_Tune_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Tune_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tune_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tune_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tune_Screen_Message_Label = lv_label_create(ui_Tune_Screen);
    lv_obj_set_width(ui_Tune_Screen_Message_Label, 300);
    lv_obj_set_height(ui_Tune_Screen_Message_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tune_Screen_Message_Label, -1);
    lv_obj_set_y(ui_Tune_Screen_Message_Label, -10);
    lv_obj_set_align(ui_Tune_Screen_Message_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tune_Screen_Message_Label, "Tuning Station");
    lv_obj_set_style_text_color(ui_Tune_Screen_Message_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tune_Screen_Message_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Tune_Screen_Message_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tune_Screen_Message_Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Tune_Screen = ui_Tune_Screen;
    uic_Tune_Screen_Message_Label = ui_Tune_Screen_Message_Label;

}
