// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine

#include "ui.h"

void ui_Volume_Screen_screen_init(void)
{
    ui_Volume_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Volume_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Volume_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volume_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Volume_Screen_Slider = lv_slider_create(ui_Volume_Screen);
    lv_slider_set_value(ui_Volume_Screen_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Volume_Screen_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Volume_Screen_Slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Volume_Screen_Slider, 222);
    lv_obj_set_height(ui_Volume_Screen_Slider, 10);
    lv_obj_set_align(ui_Volume_Screen_Slider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Volume_Screen_Slider, lv_color_hex(0x4C37FB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volume_Screen_Slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Volume_Screen_Slider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Volume_Screen_Slider,
                                                                                  lv_obj_get_style_pad_right(ui_Volume_Screen_Slider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Volume_Screen, ui_event_Volume_Screen, LV_EVENT_ALL, NULL);
    uic_Volume_Screen_Slider = ui_Volume_Screen_Slider;

}
